// File generated by the FlutterFire CLI — placeholder edition.
//
// This is NOT a real Firebase project configuration. It exists so the app
// compiles and runs out of the box in local/offline mode. Replace it with
// your own by running:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// See README.md > "Firebase setup" for the full walkthrough.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'piggy-bank-placeholder',
    authDomain: 'piggy-bank-placeholder.firebaseapp.com',
    storageBucket: 'piggy-bank-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'piggy-bank-placeholder',
    storageBucket: 'piggy-bank-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'piggy-bank-placeholder',
    storageBucket: 'piggy-bank-placeholder.appspot.com',
    iosBundleId: 'com.piggybank.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'piggy-bank-placeholder',
    storageBucket: 'piggy-bank-placeholder.appspot.com',
    iosBundleId: 'com.piggybank.app',
  );
}
